export const prompts = [
    "How do stars form in space?",
    "Best productivity tools for students",
    "Why do cats purr?",
    "History of the Roman Empire",
    "Tips for growing indoor plants",
    "What is quantum computing?",
    "Upcoming tech gadgets 2025",
    "Easy vegetarian recipes",
    "What causes lightning?",
    "How to improve mental focus?",
    "How do black holes form?",
    "What is blockchain technology?",
    "Benefits of meditation for mental health",
    "How to stay productive while working from home?",
    "What is machine learning and how does it work?",
    "The future of autonomous vehicles",
    "How do GPS systems work?",
    "Why do we dream?",
    "What are the best ways to learn a new language?",
    "How does the stock market work?",
    "What are the best ways to reduce stress?",
    "How to improve public speaking skills?",
    "What is the meaning of life according to philosophers?",
    "How do tornadoes form?",
    "What is the history of the Eiffel Tower?",
    "How do electric cars work?",
    "How to start a successful blog?",
    "Best fitness routines for beginners",
    "How does the internet work?",
    "How to boost your immune system naturally?",
    "What is the importance of time management?",
    "How to create a personal budget?",
    "What is sustainable living?",
    "How do 3D printers work?",
    "Tips for improving sleep quality",
    "What is artificial intelligence?",
    "What is the history of the internet?",
    "How do you make a good first impression?",
    "How to deal with difficult people?",
    "What are the best productivity apps for remote work?",
    "How to stay motivated when working from home?",
    "How do plants adapt to their environment?",
    "What are the benefits of walking every day?",
    "How do airplanes stay in the air?",
    "What is renewable energy?",
    "How to improve your memory?",
    "How does cryptocurrency work?",
    "How to improve writing skills?",
    "What is deep learning?",
    "How do volcanoes form?",
    "Best ways to improve your photography skills",
    "How to get rid of bad habits?",
    "What is the theory of relativity?",
    "How to learn coding for beginners?",
    "Why do we need to sleep?",
    "How do satellites orbit the Earth?",
    "How to make homemade skincare products?",
    "How does the human brain work?",
    "What is the science behind love?",
    "What are the benefits of reading books?",
    "How do vaccines work?",
    "How do solar panels work?",
    "What is the meaning of life in different cultures?",
    "What is virtual reality?",
    "How do plants produce food?",
    "What is 5G technology?",
    "How to stay organized in your personal life?",
    "What is the future of renewable energy?",
    "How do social media algorithms work?",
    "What is the history of the Great Wall of China?",
    "How do batteries work?",
    "How to make your own home workout routine?",
    "How does sound travel?",
    "What is the best way to start a business?",
    "How do human cells regenerate?",
    "How does the immune system protect us?",
    "Why do we yawn?",
    "What are the best ways to travel on a budget?",
    "How do drones work?",
    "How do we perceive color?",
    "How to build your own website?",
    "How do plants communicate with each other?",
    "What is the future of space exploration?",
    "How do we hear sounds?",
    "How do Wi-Fi networks work?",
    "What is sustainable fashion?",
    "How to meditate effectively?",
    "What are the benefits of journaling?",
    "How does the human digestive system work?",
    "What is the meaning of happiness?",
    "How do you prepare for a job interview?",
    "How to learn time management skills?",
    "What are the different types of machine learning?",
    "How does cryptocurrency mining work?",
    "How to start a podcast?",
    "What is cloud computing?",
    "How to make a great resume?",
    "How do artificial satellites help us?",
    "How to prepare for a public speech?",
    "What are the benefits of eating healthy?",
    "How to make the most of your morning routine?",
    "What is augmented reality?",
    "How do we maintain mental health?",
    "What is the future of artificial intelligence?",
    "How does GPS navigation work?",
    "How do we measure time?",
    "What is the history of the printing press?",
    "How to build a sustainable home?",
    "What is the importance of education?",
    "How to learn to play the guitar?",
    "What is the role of genetics in health?",
    "How do plants help the environment?",
    "What is the future of work?",
    "How does the human respiratory system work?",
    "How do clouds form?",
    "How does a computer process information?",
    "What is mindfulness meditation?",
    "How to create a healthy work-life balance?",
    "How does the human heart work?",
    "What are the best ways to increase creativity?",
    "How does the human nervous system work?",
    "How to build a successful startup?",
    "How to learn photography?",
    "What are the most important soft skills in the workplace?",
    "What is the future of transportation?",
    "How do plants use photosynthesis?",
    "How to build a professional network?",
    "What is the history of the internet?",
    "How to improve communication skills?",
    "How do bees communicate?",
    "How to start a YouTube channel?",
    "How does climate change affect the planet?",
    "What is the role of women in science?",
    "How do we experience emotions?",
    "How to make the perfect cup of coffee?",
    "How do volcanoes impact the environment?",
    "How do we see colors?",
    "How to get better at problem-solving?",
    "How to make homemade candles?",
    "What is the science behind happiness?",
    "How do we process information in our brain?",
    "How to stay focused while studying?",
    "How to learn self-discipline?",
    "How does the brain control the body?",
    "How does light travel through space?",
    "How do we use technology to solve problems?",
    "What are the benefits of yoga?",
    "How to stay healthy during winter?",
    "What is the role of artificial intelligence in healthcare?",
    "How do plants grow?",
    "How to build a social media presence?",
    "How do we use technology in education?",
    "How to create a successful marketing strategy?",
    "How to improve your public speaking skills?",
    "What are the different types of renewable energy?",
    "What is the role of oxygen in respiration?",
    "How does the brain process language?",
    "What is the importance of the water cycle?",
    "How to become a successful entrepreneur?",
    "How do we predict the weather?",
    "How does the circulatory system work?",
    "What is the role of enzymes in digestion?",
    "How does a compass work?",
    "How do wind turbines generate electricity?",
    "How to manage stress at work?",
    "How do you build a brand identity?",
    "What is artificial intelligence in healthcare?",
    "How to get started with cryptocurrency?",
    "How does the digestive system break down food?",
    "How to create an effective study schedule?",
    "What is deep space exploration?",
    "How do we regulate body temperature?",
    "How does the brain store memories?",
    "What is the importance of biodiversity?",
    "How to stay positive during tough times?",
    "What is the history of the telephone?",
    "How do electrical circuits work?",
    "How does a GPS work in a car?",
    "How to reduce your carbon footprint?",
    "How do we know the Earth is round?",
    "How does the solar system work?",
    "What are the benefits of a plant-based diet?",
    "How do wireless charging systems work?",
    "How to stay healthy while working remotely?",
    "What is the history of the World Wide Web?",
    "How to make a good decision?",
    "How does the ocean regulate the Earth's climate?",
    "How do we process information visually?",
    "How to improve your critical thinking skills?",
    "What is the history of space travel?",
    "How do astronauts live in space?",
    "What is the science of color perception?",
    "How does the human skeleton work?",
    "How does electricity flow through wires?",
    "What is sustainable agriculture?",
    "How to get better at decision-making?",
    "What is the importance of critical thinking?",
    "How do bioluminescent organisms work?",
    "How to develop a growth mindset?",
    "What is the science behind viral infections?"
];
